ALTER TABLE Users DROP COLUMN [Password];

ALTER TABLE Users ADD PasswordHash VARBINARY(500) NULL;
ALTER TABLE Users ADD PasswordSalt VARBINARY(500) NULL;
ALTER TABLE Users ADD [Status] BIT NULL;
ALTER TABLE Users ALTER COLUMN FirstName VARCHAR(50);
ALTER TABLE Users ALTER COLUMN LastName VARCHAR(50);
ALTER TABLE Users ALTER COLUMN Email VARCHAR(50);

CREATE TABLE OperationClaims (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(500) NULL
);

CREATE TABLE UserOperationClaims (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
	OperationClaimId INT NOT NULL FOREIGN KEY REFERENCES UserOperationClaims(Id)
);
